# Generated by Django 6.0.3 on 2026-03-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('premier', 'Premier'), ('classique', 'Classique'), ('couture', 'Couture')], max_length=20)),
                ('is_borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plan', models.CharField(choices=[('premier', 'Premier'), ('classique', 'Classique'), ('couture', 'Couture'), ('couture_plus', 'Couture Plus')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.user')),
            ],
        ),
    ]
